local M = {}

-- Collect keymaps from vim.keymap with descriptions
local function get_keymaps()
  local keymaps = {}
  local modes = { "n", "v", "i", "t", "x", "o" }

  for _, mode in ipairs(modes) do
    local mode_maps = vim.api.nvim_get_keymap(mode)
    for _, map in ipairs(mode_maps) do
      if map.desc and map.desc ~= "" then
        table.insert(keymaps, {
          mode = mode,
          lhs = map.lhs,
          desc = map.desc,
          source = map.buffer == 0 and "global" or "buffer",
        })
      end
    end
  end

  -- Sort by mode, then by lhs
  table.sort(keymaps, function(a, b)
    if a.mode ~= b.mode then
      return a.mode < b.mode
    end
    return a.lhs < b.lhs
  end)

  return keymaps
end

-- Format keymap for markdown
local function format_key(lhs)
  return "`" .. lhs:gsub("|", "\\|"):gsub("<", "\\<"):gsub(">", "\\>") .. "`"
end

-- Generate markdown content
local function generate_markdown(keymaps)
  local lines = {
    "# Keymaps",
    "",
    "> Auto-generated by `:GenerateKeymapDocs`",
    "",
    "## Leader Keys",
    "",
    "- `<space>` - Primary leader",
    "- `\\` - Local leader",
    "",
    "## All Keymaps",
    "",
    "| Mode | Key | Description |",
    "|------|-----|-------------|",
  }

  for _, km in ipairs(keymaps) do
    local line = string.format("| %s | %s | %s |", km.mode, format_key(km.lhs), km.desc)
    table.insert(lines, line)
  end

  table.insert(lines, "")
  table.insert(lines, "---")
  table.insert(lines, "")
  table.insert(lines, "*Generated: " .. os.date("%Y-%m-%d %H:%M") .. "*")

  return table.concat(lines, "\n")
end

function M.generate()
  local keymaps = get_keymaps()
  local content = generate_markdown(keymaps)

  local path = vim.fn.stdpath("config") .. "/KEYMAPS.md"
  local file = io.open(path, "w")
  if file then
    file:write(content)
    file:close()
    vim.notify("Generated " .. path .. " (" .. #keymaps .. " keymaps)", vim.log.levels.INFO)
  else
    vim.notify("Failed to write " .. path, vim.log.levels.ERROR)
  end
end

-- Register command
vim.api.nvim_create_user_command("GenerateKeymapDocs", M.generate, {
  desc = "Generate KEYMAPS.md documentation",
})

return M
