vim.keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover" })
vim.keymap.set("n", "[d", function()
  vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "Diagnostic Prev" })
vim.keymap.set("n", "]d", function()
  vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "Diagnostic Next" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Better merge lines" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Better search next" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Better search prev" })
vim.keymap.set("n", "q:", function() end, { desc = "Typo quit fix" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Automatically quit highlight mode" })
vim.keymap.set("n", "<space>tih", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "Toggle Inlay Hints" })
